name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -e ".[testing]"
      - name: Run tests with pytest
        run: |
          python setup.py --verbose test
          python3 -m pylint fixup_chooser/ test/
      - name: Run end2end tests
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "tester"
          python setup.py --verbose test
          make test-e2e
